Feature/sable cc grammar
KarmaKamikaze/STEP pull request #1
Opened 2022-03-29 12:44 UTC by KarmaKamikaze

2022-03-29 12:44 UTC, KarmaKamikaze commented
![](https://github.trello.services/images/mini-trello-icon.png) [Convert CFG draft to SableCC grammar](https://trello.com/c/N2CWFQcs/52-convert-cfg-draft-to-sablecc-grammar)

2022-03-31 09:13 UTC, mirakst commented on STEP.grammar
> +  funcdcl = {one} type brackets? T.function id params stmt* retstmt endfunction nl | {two} blank T.function id params stmt* endfunction nl;
single dimensional array only
proposed code allows multiple dimensions
```suggestion
  funcdcl = {one} type brackets* T.function id params stmt* retstmt endfunction nl | {two} blank T.function id params stmt* endfunction nl;
```

2022-03-31 09:15 UTC, mirakst commented on STEP.grammar
> +  retstmt = {one} return cond;
vi skal også kunne have et empty return, hvis vi skal have conditional returns i en blank funktion f.eks
```suggestion
  retstmt = {one} return cond | {two} return;
```

2022-03-31 09:22 UTC, mirakst commented on STEP.grammar
> +  value = {one} P.constant | {two} id | {three} lparen expr rparen;
allow array access in expressions
```suggestion
  value = {one} P.constant | {two} id arrindex? | {three} lparen expr rparen;
```

2022-03-31 09:35 UTC, Sarmisuper approved these changes

2022-03-31 09:35 UTC, Sarmisuper commented on STEP.grammar
> +  funcdcl = {one} type brackets? T.function id params stmt* retstmt endfunction nl | {two} blank T.function id params stmt* endfunction nl;
Enable return of more than one dimensional arrays

2022-03-31 09:35 UTC, Sarmisuper commented on STEP.grammar
> +  constant = {one} numliteral | {two} strliteral | {three} boolliteral;
Missing operator precendence

2022-03-31 09:35 UTC, Sarmisuper commented on STEP.grammar
> +  arr_id_or_expr = {one} id | {two} lbrack params_options? rbrack;
does not allow for multidimensional arrays

2022-03-31 09:35 UTC, mirakst commented on STEP.grammar
> +  arr_id_or_expr = {one} id | {two} lbrack params_options? rbrack;
allow multidimensional array literal
```suggestion
 arr_id_or_expr = {one} id | {two} lbrack arr_lit* rbrack;
 arr_lit = {one} params_options? | {two}  lbrack params_options? rbrack | {three} lbrack params_options? rbrack comma 
 arr_lit;
```

2022-03-31 09:37 UTC, mirakst requested changes
very nice and cool and amazing good job
pls adds suggestions

2022-03-31 09:39 UTC, KarmaKamikaze commented on STEP.grammar
> +  constant = {one} numliteral | {two} strliteral | {three} boolliteral;
We will fix it after testing

2022-03-31 09:40 UTC, mirakst approved these changes

2022-03-31 09:41 UTC, merged

2022-04-04 11:48 UTC, KarmaKamikaze commented
![](https://github.trello.services/images/mini-trello-icon.png) [Develop a lexer/scanner](https://trello.com/c/iUU1mWJF/8-develop-a-lexer-scanner)