Feature/if statement grammar fix
KarmaKamikaze/STEP pull request #8
Opened 2022-04-22 09:41 UTC by damniko

Changes:

- Grammar now supports else-if chaining within an if-statement
- A couple of AstBuilderVisitor tests were implemented specifically for if-statements
- In order for the tests to work, all nodes now override the Equals method to check structural equality (rather than reference equality)

2022-04-22 16:20 UTC, Sarmisuper requested changes
Looks very well done. Er meget fan af din måde at build if-statements i AstBuilder, den måde havde jeg ikke tænkt på, genius! Der er dog nogle ting som skal ændres someplaces, har lagt comments til det.

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/AstBuilderVisitor.cs
> +        }
Hvad hvis der ikke er nogle elseif? Maybe need null check

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/AstBuilderVisitor.cs
> +            else if(stmt.CONTINUE != null)
Her skal du nok have () efter BREAK og CONTINUE.

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/AstBuilderVisitor.cs
> +                    node.ElseClause.Add((ContNode)NodeFactory.MakeNode(AstNodeType.ContNode));
Se forrige kommentar

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/AstBuilderVisitor.cs
> +            else if (stmt.CONTINUE != null)
Forrige kommentar

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/ArrDclNode.cs
> +                && Equals(other.IdRight, IdRight);
Her mangler der noget. Der mangles at tjekke på nodernes Right property. Altså den property der bruges, når højre side af declarationen er en array literal og ikke et id

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/ArrDclNode.cs
> +                && Equals(other.IdRight, IdRight);
Siden de er null hvis de ikke sættes (altså IdRight og Right), så er det nok bare at tilføje endnu en &&

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/ForNode.cs
> +                && Body.SequenceEqual(Body);
Forkert. Burde være other.Body

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/IdNode.cs
> +                && Equals(other.IsArray, IsArray)
IsArray er obsolete. Reminder at den property skal slettes, siden at Type propertien beskriver om det er et array.

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/NegNode.cs
> +            return Equals(other.Left, Left) && Equals(other.Right, Right);
Technically correct, but wrong. På en NegNode sættes Left propertien kun. Right sættes aldrig (siden neg jo er en unary operation). Så slet tjekket om Right er equal

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/ParenNode.cs
> +            return Equals(other.Left, Left) && Equals(other.Right, Right);
Samme som ved NegNode.

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/AST/Nodes/UMinusNode.cs
> +            return Equals(other.Left, Left) && Equals(other.Right, Right);
Samme som ved NegNode

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/TypeVisitor.cs
> +        if (n.Type != TypeVal.Boolean)
This is wrong, right? Burde det ikke være n.Condition.Type != TypeVal.Boolean

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/TypeVisitor.cs
> +        if (n.Type != TypeVal.Boolean)
Og det burde jo så være .Type.ActualType tror jeg

2022-04-22 16:20 UTC, Sarmisuper commented on STEP/TypeVisitor.cs
> +            n.Type = TypeVal.Error;
Den her er dog ok i think...

2022-04-22 16:20 UTC, Sarmisuper commented on StepTests/ASTVisitorTests.cs
>          var idNode = new IdNode() { Id = "x" };
Her mangles at typen af idnoden sættes

2022-04-25 06:58 UTC, Sarmisuper commented on STEP/TypeVisitor.cs
> +            n.Type = TypeVal.Error;
Men måske igen .Type.ActualType

2022-04-25 07:56 UTC, KarmaKamikaze approved these changes
Det er fanme en lækker måde at starte mandag morgen på 👍

2022-04-25 07:56 UTC, KarmaKamikaze commented on STEP/ANTLR gens/STEP.g4
> +  NUMLITERAL                    : (DIGIT+ ('.' DIGIT*)? | '.' DIGIT+);
Do we really want this?

2022-04-25 07:56 UTC, KarmaKamikaze commented on STEP/AST/Nodes/IfNode.cs
> +            //TODO: fix this shit with SequenceEquals
👀

2022-04-25 08:11 UTC, damniko commented on STEP/ANTLR gens/STEP.g4
> +  NUMLITERAL                    : (DIGIT+ ('.' DIGIT*)? | '.' DIGIT+);
fixed! nu accepterer den kun tal med komma hvis der er tal på begge sider!

2022-04-25 08:24 UTC, mirakst approved these changes

2022-04-25 08:25 UTC, merged